#ifndef _ROS_mower_msgs_LidarMotorStatus_h
#define _ROS_mower_msgs_LidarMotorStatus_h

// Auto-generated by firmware/scripts/sync_ros_lib.py
// Do not edit manually — re-run the script after changing .msg files.

#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include "ros/msg.h"
#include "std_msgs/Header.h"

namespace mower_msgs
{

  class LidarMotorStatus : public ros::Msg
  {
    public:
      typedef std_msgs::Header _header_type;
      _header_type header;
      typedef uint8_t _state_type;
      _state_type state;
      typedef float _commanded_duty_cycle_type;
      _commanded_duty_cycle_type commanded_duty_cycle;
      typedef float _time_in_state_sec_type;
      _time_in_state_sec_type time_in_state_sec;
      enum { IDLE = 0 };
      enum { SPINNING_UP = 1 };
      enum { RUNNING = 2 };
      enum { SPINNING_DOWN = 3 };
      enum { FAULT = 4 };

    LidarMotorStatus():
      header(),
      state(0),
      commanded_duty_cycle(0),
      time_in_state_sec(0)
    {
    }

    virtual int serialize(unsigned char *outbuffer) const override
    {
      int offset = 0;
      offset += this->header.serialize(outbuffer + offset);
      *(outbuffer + offset + 0) = (this->state >> (8 * 0)) & 0xFF;
      offset += sizeof(this->state);
      union {
        float real;
        uint32_t base;
      } u_commanded_duty_cycle;
      u_commanded_duty_cycle.real = this->commanded_duty_cycle;
      *(outbuffer + offset + 0) = (u_commanded_duty_cycle.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_commanded_duty_cycle.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_commanded_duty_cycle.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_commanded_duty_cycle.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->commanded_duty_cycle);
      union {
        float real;
        uint32_t base;
      } u_time_in_state_sec;
      u_time_in_state_sec.real = this->time_in_state_sec;
      *(outbuffer + offset + 0) = (u_time_in_state_sec.base >> (8 * 0)) & 0xFF;
      *(outbuffer + offset + 1) = (u_time_in_state_sec.base >> (8 * 1)) & 0xFF;
      *(outbuffer + offset + 2) = (u_time_in_state_sec.base >> (8 * 2)) & 0xFF;
      *(outbuffer + offset + 3) = (u_time_in_state_sec.base >> (8 * 3)) & 0xFF;
      offset += sizeof(this->time_in_state_sec);
      return offset;
    }

    virtual int deserialize(unsigned char *inbuffer) override
    {
      int offset = 0;
      offset += this->header.deserialize(inbuffer + offset);
      this->state =  ((uint8_t) (*(inbuffer + offset)));
      offset += sizeof(this->state);
      union {
        float real;
        uint32_t base;
      } u_commanded_duty_cycle;
      u_commanded_duty_cycle.base = 0;
      u_commanded_duty_cycle.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_commanded_duty_cycle.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_commanded_duty_cycle.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_commanded_duty_cycle.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->commanded_duty_cycle = u_commanded_duty_cycle.real;
      offset += sizeof(this->commanded_duty_cycle);
      union {
        float real;
        uint32_t base;
      } u_time_in_state_sec;
      u_time_in_state_sec.base = 0;
      u_time_in_state_sec.base |= ((uint32_t) (*(inbuffer + offset + 0))) << (8 * 0);
      u_time_in_state_sec.base |= ((uint32_t) (*(inbuffer + offset + 1))) << (8 * 1);
      u_time_in_state_sec.base |= ((uint32_t) (*(inbuffer + offset + 2))) << (8 * 2);
      u_time_in_state_sec.base |= ((uint32_t) (*(inbuffer + offset + 3))) << (8 * 3);
      this->time_in_state_sec = u_time_in_state_sec.real;
      offset += sizeof(this->time_in_state_sec);
     return offset;
    }

    virtual const char * getType() override { return "mower_msgs/LidarMotorStatus"; };
    virtual const char * getMD5() override { return "2aa87d109fc73e3d7e94d20ed2cb5ab4"; };

  };

}
#endif
