// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/envs": {
            "get": {
                "description": "get config env from backend",
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "get config env from backend",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetConfigResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/keys/get": {
            "post": {
                "description": "get config from backend",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "get config from backend",
                "parameters": [
                    {
                        "description": "settings",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/config/keys/set": {
            "post": {
                "description": "set config to backend",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "set config to backend",
                "parameters": [
                    {
                        "description": "settings",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/containers": {
            "get": {
                "description": "list all containers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "list all containers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ContainerListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/containers/{containerId}/logs": {
            "get": {
                "description": "get container logs",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "get container logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "container id",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/containers/{containerId}/{command}": {
            "post": {
                "description": "execute a command on a container",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "containers"
                ],
                "summary": "execute a command on a container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "container id",
                        "name": "containerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "command to execute (start/stop/restart)",
                        "name": "command",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mowglinext/call/{command}": {
            "post": {
                "description": "call a service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mowglinext"
                ],
                "summary": "call a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "command to call, could be: high_level_control, emergency, mow_enabled, start_in_area",
                        "name": "command",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "CallReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mowglinext/map": {
            "put": {
                "description": "clear the map and insert all provided areas in a single transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mowglinext"
                ],
                "summary": "Delete the current map and replace all areas",
                "parameters": [
                    {
                        "description": "replace map request body",
                        "name": "CallReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mowgli.ReplaceMapReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "clear the map",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mowglinext"
                ],
                "summary": "clear the map",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mowglinext/map/area/add": {
            "post": {
                "description": "add a map area",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mowglinext"
                ],
                "summary": "add a map area",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "CallReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mowgli.AddMowingAreaReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mowglinext/map/docking": {
            "post": {
                "description": "set the docking point",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mowglinext"
                ],
                "summary": "set the docking point",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "CallReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mowgli.SetDockingPointReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mowglinext/publish/{topic}": {
            "get": {
                "description": "publish to a topic",
                "tags": [
                    "mowglinext"
                ],
                "summary": "publish to a topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "topic to publish to, could be: joy",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/mowglinext/subscribe/{topic}": {
            "get": {
                "description": "subscribe to a topic",
                "tags": [
                    "mowglinext"
                ],
                "summary": "subscribe to a topic",
                "parameters": [
                    {
                        "type": "string",
                        "description": "logical topic key: diagnostics, status, highLevelStatus, gps, pose, imu, ticks, map, path, plan, mowingPath, power, emergency, dockingSensor, lidar",
                        "name": "topic",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/schedules": {
            "get": {
                "description": "list all mowing schedules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "list all schedules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScheduleListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new mowing schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "create a schedule",
                "parameters": [
                    {
                        "description": "schedule",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Schedule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Schedule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/schedules/{id}": {
            "put": {
                "description": "update an existing mowing schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "update a schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "schedule",
                        "name": "schedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Schedule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Schedule"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete a mowing schedule",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "schedules"
                ],
                "summary": "delete a schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "description": "returns a JSON object with the settings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "returns a JSON object with the settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.GetSettingsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "saves the settings to the mower_config.sh file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "saves the settings to the mower_config.sh file",
                "parameters": [
                    {
                        "description": "settings key-value map",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/settings/schema": {
            "get": {
                "description": "returns the JSON Schema for mower configuration parameters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "returns the mower config JSON Schema",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/settings/status": {
            "get": {
                "description": "returns whether onboarding has been completed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "get settings onboarding status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SettingsStatusResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "marks onboarding as completed so the wizard is not shown again",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "mark onboarding as completed",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/settings/yaml": {
            "get": {
                "description": "returns the current YAML mower configuration values as a flat key-value map",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "returns the current YAML mower configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "saves the mower configuration as YAML to mowgli_robot.yaml",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "saves the mower configuration as YAML",
                "parameters": [
                    {
                        "description": "flat key-value settings map",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/setup/flashBoard": {
            "post": {
                "description": "flash the mower board with the given config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "setup"
                ],
                "summary": "flash the mower board with the given config",
                "parameters": [
                    {
                        "description": "config",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.FirmwareConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/system/info": {
            "get": {
                "description": "get system info such as CPU temperature",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "get system info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SystemInfo"
                        }
                    }
                }
            }
        },
        "/system/reboot": {
            "post": {
                "description": "reboots the Raspberry Pi",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "reboot the system",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/system/shutdown": {
            "post": {
                "description": "shuts down the Raspberry Pi",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "shutdown the system",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OkResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Container": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "api.ContainerListResponse": {
            "type": "object",
            "properties": {
                "containers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Container"
                    }
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.GetConfigResponse": {
            "type": "object",
            "properties": {
                "tileUri": {
                    "type": "string"
                }
            }
        },
        "api.GetSettingsResponse": {
            "type": "object",
            "properties": {
                "settings": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "api.OkResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "string"
                }
            }
        },
        "api.Schedule": {
            "type": "object",
            "properties": {
                "area": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "daysOfWeek": {
                    "description": "0=Sunday .. 6=Saturday",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "lastRun": {
                    "type": "string"
                },
                "time": {
                    "description": "HH:mm format",
                    "type": "string"
                }
            }
        },
        "api.ScheduleListResponse": {
            "type": "object",
            "properties": {
                "schedules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Schedule"
                    }
                }
            }
        },
        "api.SettingsStatusResponse": {
            "type": "object",
            "properties": {
                "onboarding_completed": {
                    "type": "boolean"
                }
            }
        },
        "api.SystemInfo": {
            "type": "object",
            "properties": {
                "cpuTemperature": {
                    "type": "number"
                }
            }
        },
        "geometry.Point": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                },
                "z": {
                    "type": "number"
                }
            }
        },
        "geometry.Point32": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                },
                "z": {
                    "type": "number"
                }
            }
        },
        "geometry.Polygon": {
            "type": "object",
            "properties": {
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/geometry.Point32"
                    }
                }
            }
        },
        "geometry.Pose": {
            "type": "object",
            "properties": {
                "orientation": {
                    "$ref": "#/definitions/geometry.Quaternion"
                },
                "position": {
                    "$ref": "#/definitions/geometry.Point"
                }
            }
        },
        "geometry.Quaternion": {
            "type": "object",
            "properties": {
                "w": {
                    "type": "number"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                },
                "z": {
                    "type": "number"
                }
            }
        },
        "mowgli.AddMowingAreaReq": {
            "type": "object",
            "properties": {
                "area": {
                    "$ref": "#/definitions/mowgli.MapArea"
                },
                "is_navigation_area": {
                    "type": "boolean"
                }
            }
        },
        "mowgli.MapArea": {
            "type": "object",
            "properties": {
                "area": {
                    "$ref": "#/definitions/geometry.Polygon"
                },
                "is_navigation_area": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "obstacles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/geometry.Polygon"
                    }
                }
            }
        },
        "mowgli.ReplaceMapArea": {
            "type": "object",
            "properties": {
                "area": {
                    "$ref": "#/definitions/mowgli.MapArea"
                },
                "is_navigation_area": {
                    "type": "boolean"
                }
            }
        },
        "mowgli.ReplaceMapReq": {
            "type": "object",
            "properties": {
                "areas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/mowgli.ReplaceMapArea"
                    }
                }
            }
        },
        "mowgli.SetDockingPointReq": {
            "type": "object",
            "properties": {
                "docking_pose": {
                    "$ref": "#/definitions/geometry.Pose"
                }
            }
        },
        "types.FirmwareConfig": {
            "type": "object",
            "properties": {
                "batChargeCutoffVoltage": {
                    "type": "number"
                },
                "boardType": {
                    "type": "string"
                },
                "bothWheelsLiftEmergencyMillis": {
                    "type": "integer"
                },
                "branch": {
                    "type": "string"
                },
                "debugType": {
                    "type": "string"
                },
                "directory": {
                    "type": "string"
                },
                "disableEmergency": {
                    "type": "boolean"
                },
                "externalImuAcceleration": {
                    "type": "boolean"
                },
                "externalImuAngular": {
                    "type": "boolean"
                },
                "file": {
                    "type": "string"
                },
                "imuOnboardInclinationThreshold": {
                    "type": "integer"
                },
                "limitVoltage150MA": {
                    "type": "number"
                },
                "masterJ18": {
                    "type": "boolean"
                },
                "maxChargeCurrent": {
                    "type": "number"
                },
                "maxChargeVoltage": {
                    "type": "number"
                },
                "maxMps": {
                    "type": "number"
                },
                "oneWheelLiftEmergencyMillis": {
                    "type": "integer"
                },
                "panelType": {
                    "type": "string"
                },
                "perimeterWire": {
                    "type": "boolean"
                },
                "playButtonClearEmergencyMillis": {
                    "type": "integer"
                },
                "repository": {
                    "type": "string"
                },
                "stopButtonEmergencyMillis": {
                    "type": "integer"
                },
                "tickPerM": {
                    "type": "number"
                },
                "tiltEmergencyMillis": {
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                },
                "wheelBase": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4200",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "MowgliNext GUI API",
	Description:      "API for the MowgliNext autonomous robot mower GUI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
