services:
  gnss_ublox:
    container_name: mowgli-gps
    image: ${MOWGLI_ROS2_IMAGE}

    network_mode: host
    ipc: host
    privileged: true

    volumes:
      - /dev:/dev
      - ./docker/config/mowgli:/config/mowgli:ro
      - ./docker/config/cyclonedds.xml:/cyclonedds.xml:ro

    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: file:///cyclonedds.xml
      ROS_AUTOMATIC_DISCOVERY_RANGE: LOCALHOST

    command: >
      ros2 launch mowgli_bringup ublox_gnss.launch.py
      ublox_device_family:=${UBLOX_DEVICE_FAMILY:-F9P}
      ublox_frame_id:=gps_link
      ublox_device_serial_string:=${GPS_PORT:-/dev/gps}

    restart: unless-stopped
